# Generated by Django 4.1.2 on 2022-11-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('alimento', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('racion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('dia_hora', models.DateTimeField()),
                ('alimento', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('dia_hora', models.DateTimeField()),
                ('dato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
