# Generated by Django 4.1.2 on 2022-11-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbohidratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='indice_glucemico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='dato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
