# Generated by Django 4.1.2 on 2022-11-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbohidratos', '0002_alimentos_indice_glucemico_alter_comida_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='alimento',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='racion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comida',
            name='alimento',
            field=models.CharField(max_length=50),
        ),
    ]
