# Generated by Django 4.1.2 on 2022-11-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbohidratos', '0003_alter_alimentos_alimento_alter_alimentos_racion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbohidratos.persona'),
        ),
    ]
