# Generated by Django 4.1.2 on 2022-12-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbohidratos', '0005_alimentos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos',
            name='imagen',
        ),
    ]
